### ISSUE TITLE
Issue with assigning variables

### ISSUE THREAD

**Issue by Natalie-J-M** [MSSanton/glmms_workflow#1]
Hi there, I'm new to GithHub so I hope this is the correct place the post an issue/question.

I've trying to use the workflow template but am having trouble assigning the variables. I have tried both "variablename" and df$variablename, but it returns this error when I try to use them in a command: **Error in `[.data.frame`(data, variables) : undefined columns selected**

What am I doing wrong here?

See example below. 

Thanks!
#================================#
# * 3.1 ONE RESPONSE variable ----
#================================#
var_resp <- NA                                  # assign default NA if missing
var_resp <- df$calling.index                     # Replace with the name of the response variable.

#=============================================================================#
# * 3.2 Fixed predictors: quantitative and categorical predictor variables ----
#=============================================================================#
# FACTOR PREDICTOR variable(s)
var_fac <- NA  # assign default NA if missing.
var_fac <- c(df$site.id, df$frog.season)     # var_fac <- c("fac_1", "fac_2", ... )   
# Template: replace entries with the name(s) of your factor predictor(s). 
# Assure all these are factors with at least two levels.

#================================#
# * 3.1 ONE RESPONSE variable ----
#================================#
var_resp <- NA                                  # assign default NA if missing
var_resp <- "calling.index"                    # Replace with the name of the response variable.

#=============================================================================#
# * 3.2 Fixed predictors: quantitative and categorical predictor variables ----
#=============================================================================#
# FACTOR PREDICTOR variable(s)
var_fac <- NA  # assign default NA if missing.
var_fac <- c("site.id", "frog.season")     # var_fac <- c("fac_1", "fac_2", ... )   
# Template: replace entries with the name(s) of your factor predictor(s). 
# Assure all these are factors with at least two levels.

**Comment by MSSanton** [comment]
Hi Natalie,

You should assign variable names as follows:

var_resp <- “calling.index”
…etc

Please make sure that all your variables are part of the dataframe, and that fixed categorical predictors are of type “factor”.

Hope this helps.
Matteo



From: Natalie-J-M ***@***.***>
Date: Tuesday, 12 September 2023 at 06:08
To: MSSanton/glmms_workflow ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MSSanton/glmms_workflow] Issue with assigning variables (Issue #1)

Hi there, I'm new to GithHub so I hope this is the correct place the post an issue/question.

I've trying to use the workflow template but am having trouble assigning the variables. I have tried both "variablename", which didn't work and df$variable but then returned this error when I try to use it in a command: Error in [.data.frame(data, variables) : undefined columns selected

What am I doing wrong here?

See example below.

Thanks!
#================================#

* 3.1 ONE RESPONSE variable ----

#================================#
var_resp <- NA # assign default NA if missing
var_resp <- df$calling.index # Replace with the name of the response variable.

#=============================================================================#

* 3.2 Fixed predictors: quantitative and categorical predictor variables ----

#=============================================================================#

FACTOR PREDICTOR variable(s)

var_fac <- NA # assign default NA if missing.
var_fac <- c(df$site.id, df$frog.season) # var_fac <- c("fac_1", "fac_2", ... )

Template: replace entries with the name(s) of your factor predictor(s).
Assure all these are factors with at least two levels.

#================================#

* 3.1 ONE RESPONSE variable ----

#================================#
var_resp <- NA # assign default NA if missing
var_resp <- "calling.index" # Replace with the name of the response variable.

#=============================================================================#

* 3.2 Fixed predictors: quantitative and categorical predictor variables ----

#=============================================================================#

FACTOR PREDICTOR variable(s)

var_fac <- NA # assign default NA if missing.
var_fac <- c("site.id", "frog.season") # var_fac <- c("fac_1", "fac_2", ... )

Template: replace entries with the name(s) of your factor predictor(s).
Assure all these are factors with at least two levels.

**Comment by Natalie-J-M** [comment]
Hi Matteo,

Thank you for getting back to me so quickly.

As previously mentioned, I did try that but it didn't work:
* 3.1 ONE RESPONSE variable ----
#================================#
var_resp <- "calling.index" # Replace with the name of the response variable.

I can confirm my variables are part of the dataframe and are correctly specified, I can use for any other function/command outside of the workflow without a problem.

Kind regards,

Natalie McLeod
BSc(Hons) | s5149399
School of Environment and Science
Griffith University
________________________________

**Comment by MSSanton** [comment]
Hi Natalie,

Please send me an email where you show me the bit of the script that gives you the error, so I can try to reproduce it. The routine works fine on my laptop.

Thanks,
Matteo



From: Natalie-J-M ***@***.***>
Date: Tuesday, 12 September 2023 at 11:46
To: MSSanton/glmms_workflow ***@***.***>
Cc: Matteo Santon ***@***.***>, Comment ***@***.***>
Subject: Re: [MSSanton/glmms_workflow] Issue with assigning variables (Issue #1)
Hi Matteo,

Thank you for getting back to me so quickly.

As previously mentioned, I did try that but it didn't work:
* 3.1 ONE RESPONSE variable ----
#================================#
var_resp <- "calling.index" # Replace with the name of the response variable.

I can confirm my variables are part of the dataframe and are correctly specified, I can use for any other function/command outside of the workflow without a problem.

Kind regards,

Natalie McLeod
BSc(Hons) | s5149399
School of Environment and Science
Griffith University
________________________________
