### ISSUE TITLE
Error when running the dotplot_num function

### ISSUE THREAD

**Issue by romulocenci** [MSSanton/glmms_workflow#2]
Dear MSSanton,

I trying to run the following function.

dotplot_num(data = df, variables = c(var_num, var_resp)) # Dotplots for all numerical predictors plus the response variable.

I have specified all numerical predictors and the response variable however it keeps sending me this error.

"Error during wrapup: undefined columns selected"

Do you know what could cause this?

**Comment by nilsanthes** [comment]
Dear romulocenci,

thanks for the request! The error occurs when at least one name of any of your selected numerical vectors is somewhat misspelled. I.e., there will be typing error somewhere in either of the following 2 code lines:

var.resp <- "Name.Response.Vector"   # The name of your response vector
var.num <-  c("Num.Vector1", "Num.Vector2", ... )  # The name(s) of your numerical vector(s)

Can you please carefully crosscheck these entries and retry?

If the error remains, I would appreciate if you could send me a small reproducible example of your dataframe so I can crosscheck.

Thanks, and best wishes!
Nils

**Comment by romulocenci** [comment]
[small_sample.csv](https://github.com/MSSanton/glmms_workflow/files/13300881/small_sample.csv)

Dear nilsanthes,

I checked the names and I didn't find any errors that I could notice.

I sent the sample of my data in this message, I see that no function from the support file is not working because of this error.

I hope you can solve the problem.

All the best,

Romulo

**Comment by romulocenci** [comment]
In addition to the sample shared, I tested in both cases in the response vector the name of the response variable as "DT richness" as character and the df$DTrichness as an integer. Both cases gave me the same message error.

**Comment by nilsanthes** [comment]
Dear Romulo,

from your hint above I take the error orignates from a typo in the name of the response vector, which is "DTrichness" (without a space character as given below).

Here is a code example that works fine for your test dataset:


source("Linear modelling workflow_support functions.R")
df <- read.csv(file = "small_sample.csv")
names(df)

var_resp <- "DTrichness"        # No space between "DT" and "richness"
var_num <- names(df[5:11]) # Some names of numerical vectors - not sure which ones are your intended predictor variables

dotplot_num(data = df, variables = c(var_num, var_resp))

Does this work out for you?

Best

Nils

**Comment by romulocenci** [comment]
Thanks for the explanation, I didn't realize that I needed to write the names like in the dataset.

All the best.

**Comment by romulocenci** [comment]
Ending this issue here.
